#!/usr/bin/env python3

"""
CupidKit - Valentine Surprise Website Generator (CLI Tool)
-----------------------------------------------------------

Author      : Karthikeyan (https://karthithehacker.com)
GitHub      : https://github.com/karthi-the-hacker
Project     : CupidKit - A CLI tool to generate and host beautiful romantic surprise websites for Valentine's Day and special occasions.

License     : Open-source for educational and personal use.

Note to Users:
--------------
💖 This tool is meant for creating romantic surprise web pages for loved ones.
🌐 Generated websites are hosted locally and can be shared publicly using tunneling tools (e.g., ngrok).
❗ If you use or modify this code, PLEASE GIVE PROPER CREDIT to the original author.

Warning to Code Thieves:
------------------------
❌ Removing this header or claiming this project as your own without credit is unethical and against open-source community principles.
🧠 Writing your own code earns respect. Copy-pasting without attribution does not.
✅ Be a respectful developer. Credit the original author and contributors.
"""

# Website generator - creates romantic HTML/CSS/JS files

import json
from pathlib import Path
from config import OUTPUT_DIR, THEMES, FILES
import qrcode
from io import BytesIO

class WebsiteGenerator:
    """Generate romantic website files"""
    
    def __init__(self, partner_name, message, theme="rose", include_music=False):
        self.partner_name = partner_name
        self.message = message
        self.theme = THEMES.get(theme, THEMES["rose"])
        self.include_music = include_music
        self.theme_name = theme
    
    def generate_html(self):
        """Generate HTML file"""
        html_content = f"""<!--
CupidKit - Valentine Surprise Website Generator
------------------------------------------------
Generated by CupidKit (https://github.com/karthi-the-hacker)
Author: Karthikeyan | License: Open-source for educational use

Created with ❤️ for {self.partner_name}
-->

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Happy Valentine's Day, {self.partner_name}! ❤️</title>
    <link rel="stylesheet" href="styles.css">
    <link href="https://fonts.googleapis.com/css2?family=Playfair+Display:wght@700&family=Poppins:wght@300;400;600&display=swap" rel="stylesheet">
</head>
<body class="theme-{self.theme_name}">
    <div class="hearts-container"></div>
    
    <div class="content-wrapper">
        <div class="card">
            <h1 class="title">Happy Valentine's Day</h1>
            <h2 class="name">{self.partner_name}</h2>
            
            <div class="message-container">
                <p class="message">{self.message}</p>
            </div>
            
            <div class="footer">
                <p class="footer-text">With all my love ❤️</p>
                <p class="timestamp">Generated on February 14, 2026</p>
            </div>
        </div>
    </div>
    
    <script src="script.js"></script>
    {self.get_music_tag()}
</body>
</html>
"""
        with open(FILES["index"], "w", encoding="utf-8") as f:
            f.write(html_content)
        return FILES["index"]
    
    def generate_css(self):
        """Generate CSS file with animations"""
        css_content = f"""/*
CupidKit - Valentine Surprise Website Generator
================================================
Generated by CupidKit (https://github.com/karthi-the-hacker)
Author: Karthikeyan | License: Open-source for educational use

Styling for {self.partner_name}'s romantic surprise website
*/

/* Romantic CSS Styling */

* {{
    margin: 0;
    padding: 0;
    box-sizing: border-box;
}}

:root {{
    --primary-color: {self.theme["primary"]};
    --secondary-color: {self.theme["secondary"]};
    --accent-color: {self.theme["accent"]};
    --bg-light: {self.theme["background_light"]};
}}

body {{
    font-family: 'Poppins', sans-serif;
    height: 100vh;
    overflow: hidden;
    display: flex;
    justify-content: center;
    align-items: center;
    background: linear-gradient(135deg, var(--bg-light) 0%, var(--primary-color) 100%);
    position: relative;
}}

.theme-rose {{
    background: linear-gradient(135deg, #FFF0F5 0%, #E91E63 100%);
}}

.theme-neon_love {{
    background: linear-gradient(135deg, #0F0E17 0%, #FF006E 100%);
}}

.theme-dark_romance {{
    background: linear-gradient(135deg, #1A1A1A 0%, #8B0000 100%);
}}

/* Floating hearts animation */
.hearts-container {{
    position: absolute;
    width: 100%;
    height: 100%;
    overflow: hidden;
    pointer-events: none;
}}

.heart {{
    position: absolute;
    font-size: 2rem;
    opacity: 0.6;
    animation: float 6s infinite ease-in;
    pointer-events: none;
}}

@keyframes float {{
    0% {{
        transform: translateY(100vh) translateX(0);
        opacity: 1;
    }}
    100% {{
        transform: translateY(-100vh) translateX(100px);
        opacity: 0;
    }}
}}

/* Content wrapper */
.content-wrapper {{
    position: relative;
    z-index: 10;
    display: flex;
    justify-content: center;
    align-items: center;
    height: 100%;
    width: 100%;
}}

/* Card styling */
.card {{
    background: rgba(255, 255, 255, 0.95);
    border-radius: 20px;
    padding: 60px 40px;
    max-width: 600px;
    width: 90%;
    box-shadow: 
        0 10px 40px rgba(0, 0, 0, 0.1),
        0 0 80px rgba({self.hex_to_rgb(self.theme["primary"])}, 0.15);
    backdrop-filter: blur(10px);
    animation: slideInCard 0.8s cubic-bezier(0.34, 1.56, 0.64, 1) forwards;
    border: 2px solid rgba(var(--primary-color), 0.1);
}}

@keyframes slideInCard {{
    from {{
        opacity: 0;
        transform: translateY(30px) scale(0.9);
    }}
    to {{
        opacity: 1;
        transform: translateY(0) scale(1);
    }}
}}

/* Title styling */
.title {{
    font-family: 'Playfair Display', serif;
    font-size: 3rem;
    color: var(--primary-color);
    text-align: center;
    margin-bottom: 20px;
    animation: glow 2s ease-in-out infinite;
    letter-spacing: 2px;
}}

@keyframes glow {{
    0%, 100% {{
        text-shadow: 
            0 0 10px {self.theme["primary"]},
            0 0 20px {self.theme["secondary"]};
    }}
    50% {{
        text-shadow: 
            0 0 20px {self.theme["primary"]},
            0 0 30px {self.theme["secondary"]},
            0 0 40px {self.theme["accent"]};
    }}
}}

/* Partner name */
.name {{
    font-family: 'Playfair Display', serif;
    font-size: 2.5rem;
    color: var(--secondary-color);
    text-align: center;
    margin-bottom: 30px;
    animation: fadeInScale 1s ease-out 0.2s forwards;
    opacity: 0;
}}

@keyframes fadeInScale {{
    from {{
        opacity: 0;
        transform: scale(0.8);
    }}
    to {{
        opacity: 1;
        transform: scale(1);
    }}
}}

/* Message container */
.message-container {{
    margin: 40px 0;
    padding: 20px 0;
    border-top: 2px solid var(--accent-color);
    border-bottom: 2px solid var(--accent-color);
    animation: fadeInScale 1s ease-out 0.4s forwards;
    opacity: 0;
}}

.message {{
    font-size: 1.3rem;
    color: #333;
    text-align: center;
    line-height: 1.8;
    font-style: italic;
    letter-spacing: 0.5px;
}}

/* Footer styling */
.footer {{
    text-align: center;
    margin-top: 40px;
    animation: fadeInScale 1s ease-out 0.6s forwards;
    opacity: 0;
}}

.footer-text {{
    font-size: 1.2rem;
    color: var(--primary-color);
    margin-bottom: 10px;
    font-weight: 600;
}}

.timestamp {{
    font-size: 0.9rem;
    color: #999;
    margin-top: 10px;
}}

/* Responsive design */
@media (max-width: 768px) {{
    .card {{
        padding: 40px 25px;
        border-radius: 15px;
    }}
    
    .title {{
        font-size: 2rem;
    }}
    
    .name {{
        font-size: 1.8rem;
    }}
    
    .message {{
        font-size: 1.1rem;
    }}
    
    .footer-text {{
        font-size: 1rem;
    }}
}}

@media (max-width: 480px) {{
    body {{
        padding: 20px;
    }}
    
    .card {{
        padding: 30px 20px;
    }}
    
    .title {{
        font-size: 1.8rem;
        margin-bottom: 15px;
    }}
    
    .name {{
        font-size: 1.4rem;
    }}
    
    .message {{
        font-size: 1rem;
    }}
    
    .heart {{
        font-size: 1.5rem;
    }}
}}
"""
        with open(FILES["styles"], "w", encoding="utf-8") as f:
            f.write(css_content)
        return FILES["styles"]
    
    def generate_js(self):
        """Generate JavaScript for animations"""
        js_content = """/*
CupidKit - Valentine Surprise Website Generator
================================================
Generated by CupidKit (https://github.com/karthi-the-hacker)
Author: Karthikeyan | License: Open-source for educational use

Interactive animations and effects for your romantic surprise website
*/

// Animation initialization and effects

document.addEventListener('DOMContentLoaded', function() {
    generateHearts();
    setupAnimations();
});

function generateHearts() {
    const container = document.querySelector('.hearts-container');
    const heartEmojis = ['❤️', '💕', '💖', '💗', '💝'];
    
    // Continuously generate falling hearts
    for (let i = 0; i < 30; i++) {
        createHeart(container, heartEmojis);
    }
    
    // Generate new hearts periodically
    setInterval(() => {
        createHeart(container, heartEmojis);
    }, 500);
}

function createHeart(container, emojis) {
    const heart = document.createElement('div');
    heart.classList.add('heart');
    heart.textContent = emojis[Math.floor(Math.random() * emojis.length)];
    
    // Random horizontal position
    const xPos = Math.random() * window.innerWidth;
    heart.style.left = xPos + 'px';
    
    // Random animation duration (6-10 seconds)
    const duration = 6 + Math.random() * 4;
    heart.style.animationDuration = duration + 's';
    
    // Random delay
    heart.style.animationDelay = Math.random() * 2 + 's';
    
    // Random horizontal drift
    const drift = -100 + Math.random() * 200;
    heart.style.setProperty('--drift', drift + 'px');
    
    // Add keyframe for drift
    const style = document.createElement('style');
    style.textContent = `
        @keyframes float {
            0% {
                transform: translateY(100vh) translateX(0);
                opacity: 1;
            }
            100% {
                transform: translateY(-100vh) translateX(${drift}px);
                opacity: 0;
            }
        }
    `;
    
    container.appendChild(heart);
    
    // Remove heart after animation completes
    setTimeout(() => {
        heart.remove();
    }, (duration + 2) * 1000);
}

function setupAnimations() {
    // Add parallax effect on mouse move
    document.addEventListener('mousemove', function(e) {
        const card = document.querySelector('.card');
        if (card) {
            const xPos = (e.clientX / window.innerWidth - 0.5) * 10;
            const yPos = (e.clientY / window.innerHeight - 0.5) * 10;
            card.style.transform = `perspective(1000px) rotateX(${yPos}deg) rotateY(${xPos}deg)`;
        }
    });
    
    // Reset transform on mouse leave
    document.addEventListener('mouseleave', function() {
        const card = document.querySelector('.card');
        if (card) {
            card.style.transform = 'perspective(1000px) rotateX(0) rotateY(0)';
        }
    });
    
    // Add pulse animation on scroll
    window.addEventListener('scroll', function() {
        const title = document.querySelector('.title');
        if (title && window.scrollY > 0) {
            title.style.filter = 'brightness(1.2)';
        } else if (title) {
            title.style.filter = 'brightness(1)';
        }
    });
}

// Ensure smooth loading
window.addEventListener('load', function() {
    document.body.style.opacity = '1';
});
"""
        with open(FILES["script"], "w", encoding="utf-8") as f:
            f.write(js_content)
        return FILES["script"]
    
    def generate_qr_code(public_url):
        """Generate QR code for the public URL"""
        try:
            qr = qrcode.QRCode(
                version=1,
                error_correction=qrcode.constants.ERROR_CORRECT_L,
                box_size=10,
                border=2,
            )
            qr.add_data(public_url)
            qr.make(fit=True)
            
            img = qr.make_image(fill_color={self.theme["primary"]}, 
                               back_color={self.theme["background_light"]})
            img.save(str(FILES["qrcode"]))
            return FILES["qrcode"]
        except Exception as e:
            print(f"Error generating QR code: {e}")
            return None
    
    def generate_all(self):
        """Generate all website files"""
        self.generate_html()
        self.generate_css()
        self.generate_js()
        return {
            "html": FILES["index"],
            "css": FILES["styles"],
            "js": FILES["script"]
        }
    
    @staticmethod
    def hex_to_rgb(hex_color):
        """Convert hex color to RGB"""
        hex_color = hex_color.lstrip('#')
        return ','.join(str(int(hex_color[i:i+2], 16)) for i in (0, 2, 4))
    
    def get_music_tag(self):
        """Get music audio tag if enabled"""
        if self.include_music:
            return """
    <audio id="bgMusic" autoplay loop style="display: none;">
        <source src="https://www.soundhelix.com/examples/mp3/SoundHelix-Song-1.mp3" type="audio/mpeg">
    </audio>
    <script>
        // Mute by default, unmute on user interaction
        const bgMusic = document.getElementById('bgMusic');
        if (bgMusic) {
            bgMusic.muted = true;
            document.addEventListener('click', () => {
                bgMusic.muted = false;
            }, { once: true });
        }
    </script>
"""
        return ""
